# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 468)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #a9a9a9;  /* Light gray, change as needed */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 10, 161, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_1.setStyleSheet("QComboBox {\n"
"    background-color: #f0f0f0;   /* Light grey background */\n"
"    border: 2px solid red;        /* Red border */\n"
"    border-radius: 4px;           /* Optional: round corners */\n"
"    padding: 2px 6px;             /* Optional: adjust padding */\n"
"}")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.verticalLayout.addWidget(self.comboBox_1)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    background-color: #f0f0f0;   /* Light grey background */\n"
"    border: 2px solid red;        /* Red border */\n"
"    border-radius: 4px;           /* Optional: round corners */\n"
"    padding: 2px 6px;             /* Optional: adjust padding */\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: #f0f0f0;   /* Light grey background */\n"
"    border: 2px solid red;        /* Red border */\n"
"    border-radius: 4px;           /* Optional: round corners */\n"
"    padding: 2px 6px;             /* Optional: adjust padding */\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    border: 2px solid red;\n"
"    border-radius: 4px;\n"
"    padding: 2px 6px;\n"
"}")
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #98fb98;  /* Pale Green */\n"
"    border: 2px solid #32cd32;   /* Lime Green Border */\n"
"    border-radius: 5px;\n"
"    color: #333;                 /* Text color */\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00fa9a;  /* Slightly darker green on hover */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 10, 401, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(480, 220, 181, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #98fb98;  /* Pale Green */\n"
"    border: 2px solid #32cd32;   /* Lime Green Border */\n"
"    border-radius: 5px;\n"
"    color: #333;                 /* Text color */\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00fa9a;  /* Slightly darker green on hover */\n"
"}")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pauseButton.setStyleSheet("QPushButton {\n"
"    background-color: #f08080;  /* Light Coral (Pale Red) */\n"
"    border: 2px solid #dc143c;  /* Crimson Red Border */\n"
"    border-radius: 5px;\n"
"    color: #333;                /* Text color */\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff6347;  /* Tomato Red on hover */\n"
"}\n"
"")
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopButton.setStyleSheet("QPushButton {\n"
"    background-color: #f08080;  /* Light Coral (Pale Red) */\n"
"    border: 2px solid #dc143c;  /* Crimson Red Border */\n"
"    border-radius: 5px;\n"
"    color: #333;                /* Text color */\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ff6347;  /* Tomato Red on hover */\n"
"}\n"
"")
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(500, 410, 161, 31))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Select script"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "2-sc1.1"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "3-sc1.2"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "4-sc1.2"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "5-sc2.1"))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "6-sc2.2"))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "7-sc3.1"))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "8-sc3.2"))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "10-sc4.1"))
        self.comboBox_1.setItemText(9, _translate("MainWindow", "11-sc4.2"))
        self.comboBox_1.setItemText(10, _translate("MainWindow", "12-sc3.1"))
        self.comboBox_1.setItemText(11, _translate("MainWindow", "13-sc2.1"))
        self.comboBox_1.setItemText(12, _translate("MainWindow", "14-sc2.2"))
        self.comboBox_1.setItemText(13, _translate("MainWindow", "15-sc3.1"))
        self.comboBox_1.setItemText(14, _translate("MainWindow", "17-sc4.2"))
        self.comboBox_1.setItemText(15, _translate("MainWindow", "18-sc4.1"))
        self.comboBox_1.setItemText(16, _translate("MainWindow", "19-sc1.1"))
        self.comboBox_1.setItemText(17, _translate("MainWindow", "20-sc1.2"))
        self.comboBox_2.setPlaceholderText(_translate("MainWindow", "Select weather"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select weather"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Rainy"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Sunny"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Windy"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Stormy"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Select time of day"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Early Morning"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Morning"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Afternoon"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Evening"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Night"))
        self.label.setText(_translate("MainWindow", "Enter time interval"))
        self.pushButton.setText(_translate("MainWindow", "Run Interval Analysis"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.commandLinkButton.setText(_translate("MainWindow", "View Alarm Trends"))
