# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 469)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #a9a9a9;  /* Light gray, change as needed */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 110, 361, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(430, 110, 221, 221))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 51, 21))
        self.label.setObjectName("label")
        self.comboBoxW = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxW.setGeometry(QtCore.QRect(110, 20, 91, 21))
        self.comboBoxW.setObjectName("comboBoxW")
        self.comboBoxW.addItem("")
        self.comboBoxW.addItem("")
        self.comboBoxW.addItem("")
        self.comboBoxW.addItem("")
        self.comboBoxToD = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxToD.setGeometry(QtCore.QRect(310, 20, 91, 21))
        self.comboBoxToD.setObjectName("comboBoxToD")
        self.comboBoxToD.addItem("")
        self.comboBoxToD.addItem("")
        self.comboBoxToD.addItem("")
        self.comboBoxToD.addItem("")
        self.comboBoxToD.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 60, 61, 21))
        self.label_4.setObjectName("label_4")
        self.spinBoxint1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxint1.setGeometry(QtCore.QRect(110, 60, 91, 21))
        self.spinBoxint1.setObjectName("spinBoxint1")
        self.spinBoxint2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxint2.setGeometry(QtCore.QRect(310, 60, 91, 21))
        self.spinBoxint2.setObjectName("spinBoxint2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 40, 51, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #98fb98;  /* Pale Green */\n"
"    border: 2px solid #32cd32;   /* Lime Green Border */\n"
"    border-radius: 5px;\n"
"    color: #333;                 /* Text color */\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #00fa9a;  /* Slightly darker green on hover */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(540, 410, 111, 31))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Weather:"))
        self.comboBoxW.setItemText(0, _translate("MainWindow", "Rainy"))
        self.comboBoxW.setItemText(1, _translate("MainWindow", "Sunny"))
        self.comboBoxW.setItemText(2, _translate("MainWindow", "Windy"))
        self.comboBoxW.setItemText(3, _translate("MainWindow", "Stormy"))
        self.comboBoxToD.setItemText(0, _translate("MainWindow", "Early Morning"))
        self.comboBoxToD.setItemText(1, _translate("MainWindow", "Morning"))
        self.comboBoxToD.setItemText(2, _translate("MainWindow", "Afternoon"))
        self.comboBoxToD.setItemText(3, _translate("MainWindow", "Evening"))
        self.comboBoxToD.setItemText(4, _translate("MainWindow", "Night"))
        self.label_2.setText(_translate("MainWindow", "Time of Day:"))
        self.label_3.setText(_translate("MainWindow", "From Interval:"))
        self.label_4.setText(_translate("MainWindow", "To Interval:"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.commandLinkButton.setText(_translate("MainWindow", "Go Back"))
